name: Main App Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (workflow context only)
        uses: actions/checkout@v3

      - name: Setup SSH authentication
        run: |
          mkdir -p ~/.ssh

          # Inject SSH private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_to_server
          chmod 600 ~/.ssh/github_to_server

          # Trust VPS host
          ssh-keyscan -H 91.134.143.115 >> ~/.ssh/known_hosts

          # SSH config
          cat <<EOF > ~/.ssh/config
          Host ovh-pole-g-server
            HostName 91.134.143.115
            User pole-g-plagix
            IdentityFile ~/.ssh/github_to_server
            IdentitiesOnly yes
          EOF

          chmod 600 ~/.ssh/config

      - name: Deploy, Build and Restart
        run: |
          ssh ovh-pole-g-server bash -s << 'ENDSSH'
            set -e

            # Injection directe du PATH pour cet utilisateur CloudPanel
            export PATH="/home/pole-g-plagix/.nvm/versions/node/v22.22.3/bin:$PATH"

            echo "Node: $(node -v)"
            echo "NPM: $(npm -v)"

            # Dossier créé par CloudPanel pour pole-g-plagix.org
            APP_DIR="/home/pole-g-plagix/htdocs/plagix.pole-g.org"
            SHARED_DIR="/home/pole-g-plagix/shared"
            REPO="git@github.com:hicodingx/plagix-frontend.git"
            BRANCH="main"
            APP_NAME="pole-g-plagix"

            cd "$APP_DIR"

            # Prevent Git safe.directory issue
            git config --global --add safe.directory "$APP_DIR"

            if [ ! -d .git ]; then
              echo "First deploy safe mode"
              git clone -b "$BRANCH" "$REPO" .
            else
              echo "Updating code safely"
              git fetch origin
              git reset --hard origin/$BRANCH
              git clean -fd
            fi

            # Gestion du fichier .env de production
            if [ -f "$APP_DIR/.env" ]; then
              echo "Production .env file already exists in application directory. Skipping import."
            elif [ -f "$SHARED_DIR/.env" ]; then
              echo "Importing production .env file from shared directory (first deploy)."
              cp "$SHARED_DIR/.env" "$APP_DIR/.env"
            else
              echo "ERROR: Production .env file not found anywhere."
              exit 1
            fi

            # Install dependencies
            npm ci

            # Build application
            npm run build

            # ici on s'assure d'avoir ajouté un port lisible par pm2 dans .env*
            if pm2 describe "$APP_NAME" > /dev/null 2>&1; then
              echo "Reloading Frontend and updating environment"
              pm2 reload "$APP_NAME" --update-env
            else
              echo "Starting Frontend for the first time"
              pm2 start npm --name "$APP_NAME" -- start
            fi

            # Persist PM2 state
            pm2 save

          ENDSSH